// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCriFrq7qqb8tjcNvDI378DjSo3lSrpzig',
    appId: '1:624435254521:web:31a1801bdef37fc1933e28',
    messagingSenderId: '624435254521',
    projectId: 'midterm-practice-b6ebe',
    authDomain: 'midterm-practice-b6ebe.firebaseapp.com',
    storageBucket: 'midterm-practice-b6ebe.firebasestorage.app',
    measurementId: 'G-8053X4Q3X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP52-ack19CC_UBoqQ6uWn_ah8_76OIFA',
    appId: '1:624435254521:android:645331cf431ca6fa933e28',
    messagingSenderId: '624435254521',
    projectId: 'midterm-practice-b6ebe',
    storageBucket: 'midterm-practice-b6ebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhujhC2UfW7g8st_UfYMU42cLo4GhssfA',
    appId: '1:624435254521:ios:eb317479a374d7c5933e28',
    messagingSenderId: '624435254521',
    projectId: 'midterm-practice-b6ebe',
    storageBucket: 'midterm-practice-b6ebe.firebasestorage.app',
    iosBundleId: 'com.example.midtermPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhujhC2UfW7g8st_UfYMU42cLo4GhssfA',
    appId: '1:624435254521:ios:eb317479a374d7c5933e28',
    messagingSenderId: '624435254521',
    projectId: 'midterm-practice-b6ebe',
    storageBucket: 'midterm-practice-b6ebe.firebasestorage.app',
    iosBundleId: 'com.example.midtermPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCriFrq7qqb8tjcNvDI378DjSo3lSrpzig',
    appId: '1:624435254521:web:05feb982133177a9933e28',
    messagingSenderId: '624435254521',
    projectId: 'midterm-practice-b6ebe',
    authDomain: 'midterm-practice-b6ebe.firebaseapp.com',
    storageBucket: 'midterm-practice-b6ebe.firebasestorage.app',
    measurementId: 'G-19VBK7R3S1',
  );
}
